db:
  build: db
  volumes_from:
    - db-data

app:
  build: app
  links:
    - db

web:
  build: web
  links:
    - app
  ports:
    - 80:80

batch:
  build: app
  links:
    - db
  command: python3 -m app.batch
